#!/bin/bash
### BEGIN INIT INFO
# Provides:          plant
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start HACMS plant at boot time
# Description:       Enable HACMS plant start/stop
### END INIT INFO# plant daemon

PATH=/usr/sbin:/usr/bin:/sbin:/bin
NAME=plant
DESC="HACMS plant components start up script"

start_plant () {  
  /opt/hacms/etc/startup.sh
}

stop_plant () {
  /opt/hacms/etc/shutdown.sh
}

case "$1" in
  start)
    printf "%-50s" "Starting ${HOSTNAME} $NAME..."
    start_plant
    printf "Ok\n"
    ;;
  stop)
    printf "%-50s" "Stopping ${HOSTNAME} $NAME"
    stop_plant
    printf "Ok\n"
    ;;
  status)
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1
esac

