<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <property name="gps_garmin19x_z" value="0.0495" />
  <property name="gps_garmin19x_r" value="0.04805" />
 
  <xacro:macro name="gps_garmin19x" params="name parent *origin">

    <joint name="${parent}_${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}"/>
    </joint>

    <link name="${name}">
      <inertial>
        <mass value="0.2" />
        <origin xyz="0 0 ${gps_garmin19x_z/2}" />
        <inertia ixx="0.1" ixy="0" ixz="0"
                 iyy="0.1" iyz="0" izz="0.1" />
      </inertial>

      <visual>
        <origin xyz="0 0 ${gps_garmin19x_z/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${gps_garmin19x_z}" radius="${gps_garmin19x_r}"/>
        </geometry>
        
        <material name="White" />
      </visual>

      <collision>
        <origin xyz="0 0 ${gps_garmin19x_z/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${gps_garmin19x_z}" radius="${gps_garmin19x_r}"/>
        </geometry>
      </collision>
    </link>

  </xacro:macro>

</robot>
