<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <property name="umpr31_x" value="0.03038" />
  <property name="umpr31_y" value="0.095" />
  <property name="umpr31_z" value="0.085" />

  <xacro:macro name="smartmicro_umpr31" params="name parent *origin">

    <joint name="${parent}_${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}"/>
    </joint>

    <link name="${name}">
      <inertial>
        <mass value="0.2" />
        <origin xyz="${-umpr31_x/2} 0 0" />
        <inertia ixx="0.1" ixy="0" ixz="0"
                 iyy="0.1" iyz="0" izz="0.1" />
      </inertial>

      <visual>
        <origin xyz="${-umpr31_x/2} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${umpr31_x} ${umpr31_y} ${umpr31_z}"/>
        </geometry>
        
        <material name="White" />
      </visual>

      <collision>
        <origin xyz="${-umpr31_x/2} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${umpr31_x} ${umpr31_y} ${umpr31_z}"/>
        </geometry>
      </collision>
    </link>

  </xacro:macro>

</robot>
